title: Cesar's Ramirez CIT_480 Blog1
logo: /assets/img/Docker_New.png
description: A Complete blog for Tools and Technology for the CIT comunity
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
